version : '3'



services:
        web:
            image: python:3
            restart: always
            ports:
               - "5000:5000"

  

        createservice: 
                    image: mypromeapp:latest
                    build: create_service_prometheus.py


        prometheus:
                    image: prom/prometheus:latest
                    command:
                               - '--config.file=/etc/prometheus/prometheus.yml'
                               - '--storage.tsdb.path=/prometheus'
                               - '--web.console.libraries=/etc/prometheus/console_libraries'
                               - '--web.console.templates=/etc/prometheus/consoles'
                               - '--storage.tsdb.retention=200h'
                               - '--web.enable-lifecycle'
                    restart: unless-stopped
                    expose:
                      - 9090
                    ports:
                       - "9090:9090"




         


